version: '3.8'

services:
  app:
    image: my-docker-image
    container_name: my-docker-container
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8000 hospital_site.wsgi:application"
