# Generated by Django 4.2.3 on 2023-08-16 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 11, 51, 38, 384622)),
        ),
        migrations.AlterField(
            model_name='career',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 11, 51, 38, 384622)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 11, 51, 38, 382622)),
        ),
    ]
