# Generated by Django 4.2.3 on 2024-08-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hospital_customuser_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='phone_number_1',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone_number_2',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
