# Generated by Django 4.2.3 on 2023-08-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
