# Generated by Django 4.2.3 on 2023-08-17 08:10

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_patient_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='visit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now=True, null=True)),
                ('scan_type', models.CharField(max_length=50)),
                ('findings', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientvisit')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_technician', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='scan_reports/')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('scan_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_images', to='patients.scanreport')),
            ],
        ),
    ]
