# Generated by Django 4.2.3 on 2023-08-20 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_alter_patientvisit_admission_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanreport",
            name="patient",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="patients.patient"
            ),
        ),
    ]
