# Generated by Django 4.2.3 on 2023-08-21 10:21

from django.db import migrations

# import froala_editor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0007_scanreport_patient"),
    ]

    operations = []
