# Generated by Django 4.2.3 on 2023-09-06 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hospital_customuser_hospital'),
        ('patients', '0009_patient_address_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientvisits', to='core.hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='inpatient_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='outpatient_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
