# Generated by Django 4.2.3 on 2023-09-08 10:35

from django.db import migrations, models

import patients.models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0009_patient_address_patient_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanimage",
            name="image_file",
            field=models.FileField(upload_to=patients.models.upload_to_scan_images),
        ),
    ]
