name: Collect Static Files

on:
  push:
    branches:
      - master

jobs:
  collect_static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Change working directory
        run: cd hospital_site
      - name: Collect Static Files
        run: python manage.py collectstatic
      - name: Install Requirements
        run : pip install -r requirements.txt